### ISSUE TITLE
Add invisible to send_ functions

### ISSUE THREAD

**Issue by odderaser** [EriqLaplus/discordr#2]
The R base function `invisible` allows the last line of a function to be automatically returned. Replacing this on functions where `httr::POST` calls are made would be helpful. See the [slackr](https://github.com/hrbrmstr/slackr/blob/master/R/gg_slackr.R) implementation of sending ggplots.

**Comment by EriqLaplus** [comment]
This issue still lingers for send_message and send_console until a list of responses can be implemented for potentially many responses.

**Comment by EriqLaplus** [comment]
Fixed with latest build.
