### ISSUE TITLE
Send console with dataframes

### ISSUE THREAD

**Issue by jacobmunson** [EriqLaplus/discordr#7]
If you send a statement such as 
`send_console(df %>% print(n = num) ` 
then nothing is sent. 
Alternatively, you *could* save
`x = df %>% print(n = num)`
and use 
`send_console(x)`
but this also does not send "num" lines of df.

**Comment by EriqLaplus** [comment]
In trying to reproduce this, I have the following examples.

1. ```x <- tibble(x = rnorm(1000), y = rnorm(1000))
   send_console(print(x, n = 100))```

This produces an example where 100 rows are printed in Discord.

2. ```send_console(x %>% print(n = 100))```

This also produces an example where 100 rows are printed in Discord.

3. Dataframes do not have an `n` argument for the print statement unless tidyverse overwrites something this function on import which removes this functionality (unlikely). This does not apply for this case. 

4. I cannot reproduce `x = df %>% print(n = num)` to be able to print the specific number of rows.

A few questions:

1. Are you using a tibble as a dataframe?
2. Are you using any other `sink` calls for capturing output?
3. Can you provide an example of a function call and associated discord output using a dataframe of similar structure to the one you have tried to print?

**Comment by EriqLaplus** [comment]
@jacobmunson Any further testing on these items?

**Comment by EriqLaplus** [comment]
@jacobmunson I've worked on this issue today, and was able to replicate it. For send_console, there is now a `tibble_formatting` option which will allow you to specify tibble optimized line breaks. Let me know if this resolves the issue.
